name: Go
on:
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
           node-version: 16
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
      - name: Install dependencies
        run: go mod download
      - name: Test with the Go CLI
        run: go test -v ./...