name: Go
on:
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - run: go test ./...
