name: TS

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: 21.x
            - name: Install dependencies
              run: pnpm install
            - name: Lint
              run: |
               cd packages/web
               pnpm run lint
